version: '3.8'

services:
  web:
    build: .
    container_name: pizza_shop_web
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db
    networks:
      - pizza_network

  db:
    image: mysql:8.0
    container_name: pizza_shop_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: pizza_shop
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./src/initiate_db.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    networks:
      - pizza_network

networks:
  pizza_network:
    driver: bridge
